// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACSj0aONgtGjoMqeTb-Fbcym69ofvxejA',
    appId: '1:820864751632:web:5a298b295ca66e02965295',
    messagingSenderId: '820864751632',
    projectId: 'farmvaile',
    authDomain: 'farmvaile.firebaseapp.com',
    storageBucket: 'farmvaile.firebasestorage.app',
    measurementId: 'G-K3CDC87X79',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0EEHELHcOGx1BnSBEl1gtiNxe9IIHoYU',
    appId: '1:820864751632:ios:7de40fd8843f5f16965295',
    messagingSenderId: '820864751632',
    projectId: 'farmvaile',
    storageBucket: 'farmvaile.firebasestorage.app',
    iosBundleId: 'com.example.farmvaile',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoJYgpcqBTERq0yST2FqtYpueeUquSGKE',
    appId: '1:820864751632:android:8a9c2075fc71f34c965295',
    messagingSenderId: '820864751632',
    projectId: 'farmvaile',
    storageBucket: 'farmvaile.firebasestorage.app',
  );

}